//go:build !ignore_autogenerated

/*
Copyright 2025 Aneesh Puttur.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	"k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EndpointPickerSpec) DeepCopyInto(out *EndpointPickerSpec) {
	*out = *in
	in.Plugins.DeepCopyInto(&out.Plugins)
	in.Resources.DeepCopyInto(&out.Resources)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EndpointPickerSpec.
func (in *EndpointPickerSpec) DeepCopy() *EndpointPickerSpec {
	if in == nil {
		return nil
	}
	out := new(EndpointPickerSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GatewaySpec) DeepCopyInto(out *GatewaySpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GatewaySpec.
func (in *GatewaySpec) DeepCopy() *GatewaySpec {
	if in == nil {
		return nil
	}
	out := new(GatewaySpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *InferenceScheduler) DeepCopyInto(out *InferenceScheduler) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new InferenceScheduler.
func (in *InferenceScheduler) DeepCopy() *InferenceScheduler {
	if in == nil {
		return nil
	}
	out := new(InferenceScheduler)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *InferenceScheduler) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *InferenceSchedulerList) DeepCopyInto(out *InferenceSchedulerList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]InferenceScheduler, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new InferenceSchedulerList.
func (in *InferenceSchedulerList) DeepCopy() *InferenceSchedulerList {
	if in == nil {
		return nil
	}
	out := new(InferenceSchedulerList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *InferenceSchedulerList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *InferenceSchedulerSpec) DeepCopyInto(out *InferenceSchedulerSpec) {
	*out = *in
	in.ModelServer.DeepCopyInto(&out.ModelServer)
	in.EndpointPicker.DeepCopyInto(&out.EndpointPicker)
	out.Gateway = in.Gateway
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new InferenceSchedulerSpec.
func (in *InferenceSchedulerSpec) DeepCopy() *InferenceSchedulerSpec {
	if in == nil {
		return nil
	}
	out := new(InferenceSchedulerSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *InferenceSchedulerStatus) DeepCopyInto(out *InferenceSchedulerStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new InferenceSchedulerStatus.
func (in *InferenceSchedulerStatus) DeepCopy() *InferenceSchedulerStatus {
	if in == nil {
		return nil
	}
	out := new(InferenceSchedulerStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ModelServerSpec) DeepCopyInto(out *ModelServerSpec) {
	*out = *in
	in.Resources.DeepCopyInto(&out.Resources)
	if in.GPUMemoryUtilization != nil {
		in, out := &in.GPUMemoryUtilization, &out.GPUMemoryUtilization
		*out = new(float64)
		**out = **in
	}
	if in.Labels != nil {
		in, out := &in.Labels, &out.Labels
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ModelServerSpec.
func (in *ModelServerSpec) DeepCopy() *ModelServerSpec {
	if in == nil {
		return nil
	}
	out := new(ModelServerSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PluginConfig) DeepCopyInto(out *PluginConfig) {
	*out = *in
	if in.LoadAwareScorer != nil {
		in, out := &in.LoadAwareScorer, &out.LoadAwareScorer
		*out = new(ScorerPlugin)
		(*in).DeepCopyInto(*out)
	}
	if in.PrefixCacheScorer != nil {
		in, out := &in.PrefixCacheScorer, &out.PrefixCacheScorer
		*out = new(ScorerPlugin)
		(*in).DeepCopyInto(*out)
	}
	if in.KVCacheUtilizationScorer != nil {
		in, out := &in.KVCacheUtilizationScorer, &out.KVCacheUtilizationScorer
		*out = new(ScorerPlugin)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PluginConfig.
func (in *PluginConfig) DeepCopy() *PluginConfig {
	if in == nil {
		return nil
	}
	out := new(PluginConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ScorerPlugin) DeepCopyInto(out *ScorerPlugin) {
	*out = *in
	if in.Weight != nil {
		in, out := &in.Weight, &out.Weight
		*out = new(float64)
		**out = **in
	}
	if in.Parameters != nil {
		in, out := &in.Parameters, &out.Parameters
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ScorerPlugin.
func (in *ScorerPlugin) DeepCopy() *ScorerPlugin {
	if in == nil {
		return nil
	}
	out := new(ScorerPlugin)
	in.DeepCopyInto(out)
	return out
}
